name: ani
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # General
  - python=3.8
  - pip
  - typing_extensions>=4.0.0

  # Core
  - numpy>=1.26
  - pytorch=2.3
  - pytorch-cuda=11.8

  # Data
  - h5py  # HDF5 backend
  - pyyaml  # builtin datasets specification

  # Utils
  - tqdm  # progress bar

  # Ase interface (optional)
  - ase

  # Neurochem files (legacy)
  - lark-parser
  - requests
