name: ani
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # general
  - python=3.8.1
  - pip

  # Data
  - h5py  # HDF5 backend

  # DL
  - numpy=1.20
  - pytorch=1.13.1
  - cudatoolkit=11.6

  # progress bars
  - tqdm
  - pkbar

  # legacy neurochem parser
  - lark-parser
  - pyyaml

  # downloading models via web
  - requests

  # ase interface
  - ase
