name: ani-dev
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # General
  - python=3.8
  - pip
  - typing_extensions>=4.0.0

  # Core
  - numpy>=1.26
  - pytorch=2.3
  - pytorch-cuda=11.8

  # Data
  - h5py  # HDF5 backend
  - pyyaml  # builtin datasets specification

  # Utils
  - tqdm  # progress bar

  # Neurochem files (legacy)
  - lark-parser
  - requests

  # Ase interface
  - ase

  # Linters / checkers / tests-runners / CI
  - black
  - flake8
  - mypy
  - coverage
  - pytest
  - parameterized

  # Indirect dependencies of torch.testing
  - hypothesis
  - expecttest

  # Extra data backends for tests
  - pandas  # csv support
  - pyarrow  # Parquet backend
  - zarr  # Zarr backend

  # Utils for running tools
  - matplotlib
  - pynvml

  # Docs
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorboard
