name: conda

on: pull_request

env:
  REGISTRY: ${{ github.repository }}
  IMAGE_NAME: 'conda-pkg'

jobs:
  build-pkg:
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: conda.Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          shm-size: 2g
          ulimit: |
            memlock=-1
            stack=67108864

      - name: Build pkg locally
        run: >-
          docker run
          --rm
          --gpus '"device=all"'
          --shm-size=2g
          --ulimit memlock=-1
          --ulimit stack=67108864
          ${{ steps.meta.outputs.tags }}
          bash -c "source /opt/conda/etc/profile.d/conda.sh
          && conda activate
          && conda build -c nvidia -c pytorch -c conda-forge --no-anaconda-upload ./conda/recipe"

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: docker image rm ${{ steps.meta.outputs.tags }}

concurrency:
  group: conda-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
