name: conda-build

on:
  pull_request:
    paths:
      - 'setup.py'
      - 'torchani/csrc/**'
      - 'torchani/aev/**'
      - 'ci/**'
      - 'test/test_cuaev.py'
  push:
    branches:
      - master
    paths:
      - 'setup.py'
      - 'torchani/cuaev/**'
      - 'torchani/aev.py'
      - 'ci/**'
      - 'test/test_cuaev.py'

jobs:
  conda-build:

    runs-on: [self-hosted, miniconda]
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Use saved pkgs
      run: |
        if [ -d /root/conda_pkgs_dir_saved ]; then
          mv /root/conda_pkgs_dir_saved /root/conda_pkgs_dir
        fi
    - name: Set up conda path prefix
      run: |
        echo "CONDA=/root/miniconda" >> $GITHUB_ENV
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: foo
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Fetch submodules
      run: git submodule update --init
    # - name: Install cuda
    #   run: |
    #     source ci/install_cuda.sh
    #     echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
    #     echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
    #     echo "PATH=${CUDA_HOME}/bin:$PATH" >> $GITHUB_ENV
    # - name: Conda Build
    #   run: |
    #     echo $CUDA_HOME
    #     echo $LD_LIBRARY_PATH
    #     nvcc -V
    #     ./conda/build_conda.sh
    - name: Saved pkgs to avoid to be removed
      run: mv /root/conda_pkgs_dir /root/conda_pkgs_dir_saved

concurrency:
  group: conda-build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true