name: conda-build

on:
  pull_request:
    paths:
      - 'setup.py'
      - 'torchani/csrc/**'
      - 'torchani/aev/**'
      - 'ci/**'
      - 'conda/**'
      - 'test/test_cuaev.py'
  push:
    branches:
      - master
    paths:
      - 'setup.py'
      - 'torchani/csrc/**'
      - 'torchani/aev/**'
      - 'ci/**'
      - 'conda/**'
      - 'test/test_cuaev.py'

jobs:
  conda-build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: foo${{ matrix.python-version }}
        auto-update-conda: false
        python-version: ${{ matrix.python-version }}
    - name: Set up conda path prefix
      run: |
        echo "CONDA=$(conda info --base)" >> $GITHUB_ENV
    - name: Conda info
      shell: bash -l {0}
      run: conda info
    - name: Fetch submodules
      run: git submodule update --init
    - name: Conda Build
      run: |
        echo $CUDA_HOME
        echo $LD_LIBRARY_PATH
        nvcc -V
        export PYTHON_VERSION=${{ matrix.python-version }}
        export CONDA_TOKEN=${{ secrets.CONDA_TOKEN }}
        ./conda/build_conda.sh

concurrency:
  group: conda-build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true