name: cuda

on:
  pull_request:
    paths:
      - 'setup.py'
      - 'torchani/csrc/**'
      - 'torchani/aev/**'
      - 'ci/**'
      - 'test/test_cuaev.py'
  push:
    branches:
      - master
    paths:
      - 'setup.py'
      - 'torchani/cuaev/**'
      - 'torchani/aev.py'
      - 'ci/**'
      - 'test/test_cuaev.py'

jobs:
  cuda:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        torch-version: ['stable', 'nightly']
        cuda: ['cuda']

    steps:
    - name: Install Torchani with ${{ matrix.cuda }}, python ${{ matrix.python-version}} and torch ${{ matrix.torch-version }}
      uses: ./.github/actions/install_torchani
      with: 
        token: ${{ github.token }}
        python-version: ${{ matrix.python-version }}
        cuda: ${{ matrix.cuda }}
        torch-version: ${{ matrix.torch-version }}

    - name: Run cuaev test
      run: pytest tests/test_cuaev.py -v
