name: deploy-testpypi

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy-testpypi:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: deploy
        run: |
          python -m pip install build twine
          python -m build
          twine upload -u zasdfgbnm-bot -p ${{secrets.zasdfgbnm_bot_test_pypi_password}} --repository testpypi dist/*
