name: flake8

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  flake8:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        cuda: ['no-cuda']
        torch-version: ['nightly']

    - name: Install Torchani with ${{ matrix.cuda }}, python ${{ matrix.python-version}} and torch ${{ matrix.torch-version }}
      uses: ./.github/actions/install_torchani
      with: 
        token: ${{ github.token }}
        python-version: ${{ matrix.python-version }}
        cuda: ${{ matrix.cuda }}
        torch-version: ${{ matrix.torch-version }}

    - name: Install flake8
      run: pip install --upgrade flake8

    - name: Lint with flake8
      run: flake8 .
