name: lint

on: pull_request

jobs:
  clang-format:
    runs-on: [self-hosted, ipickering]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Check that clang-format is available
      run: which clang-format; clang-format --version
    - name: Lint with clang-format
      run: |
        find -name '*.cpp' -o -name '*.h' -o -name '*.cu' -o -name '*.cuh' | xargs clang-format -i
        GIT_DIFF=$(git diff)
        if [[ -z $GIT_DIFF ]]; then
            exit 0
        fi
        echo $GIT_DIFF
        exit 1

concurrency:
  group: lint-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
