name: mypy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mypy:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: create venv
      run: python -m venv /tmp/torchani-mypy
    # mypy changes the way it type checks depending on the installed
    # dependencies, so even for just type checking we install everything as we
    # would normally do
    - name: Install dependencies
      run: |
          source /tmp/torchani-unittest/bin/activate
          ci/install_dependencies.sh
    - name: Install TorchANI
      run: |
          source /tmp/torchani-unittest/bin/activate
          python setup.py install
    - name: Install mypy
      run: |
          source /tmp/torchani-unittest/bin/activate
          pip install --upgrade --no-cache-dir mypy
    - name: Type checking with mypy
      run: |
        source /tmp/torchani-mypy/bin/activate
        mypy .
    - name: remove venv
      if: always()
      run: rm -rf /tmp/torchani-mypy/
