name: tools

on: pull_request

jobs:
  tools:
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}/tools

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Inference benchmark
        run: docker run --rm --gpus all --shm-size 1g --ulimit memlock=-1 --ulimit stack=67108864 ${{ steps.meta.outputs.tags }} bash -c "python tools/inference-benchmark.py --no-tqdm"

      - name: COMP6v1 accuracy benchmark
        run: docker run --rm --gpus all --shm-size 1g --ulimit memlock=-1 --ulimit stack=67108864 ${{ steps.meta.outputs.tags }} bash -c "python tools/comp6-accuracy-benchmark.py --no-tqdm"
      - name: Training benchmark (with Nsight dry run)
        run: docker run --rm --gpus all --shm-size 1g --ulimit memlock=-1 --ulimit stack=67108864 ${{ steps.meta.outputs.tags }} bash -c "python tools/training-benchmark.py --nvtx --no-tqdm"
      - name: MD Benchmark (with Nsight dry run)
        run: docker run --rm --gpus all --shm-size 1g --ulimit memlock=-1 --ulimit stack=67108864 ${{ steps.meta.outputs.tags }} bash -c "python tools/md-benchmark.py --nvtx --no-tqdm"

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: docker image rm ${{ steps.meta.outputs.tags }}

concurrency:
  group: tools-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
