name: unittests-cpu

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unittests-cpu:
    runs-on: [self-hosted, ipickering]

    steps:
      - name: Checkout torchani
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Download test data
        run: ./download.sh
      - name: Install and Run tests
        run: >-
            docker run
            --rm
            --gpus '"device=none"'
            --privileged
            -v $PWD:/torchani_sandbox pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel
            bash
            -c
            "cd /torchani_sandbox
            && pip install 'setuptools>=61' 'setuptools_scm>=8'
            && pip install -r tests_requirements.txt
            && pip install -e .
            && cd tests/
            && pytest -v ."

concurrency:
  group: unittests-cpu-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
