name: unittests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unittests:

    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.6]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: create venv
      run: python -m venv /tmp/torchani-ci
    - name: Fetch submodules
      run: git submodule update --init
    - name: Install dependencies
      run: |
          source /tmp/torchani-ci/bin/activate
          ci/install_dependencies.sh
    - name: Install TorchANI
      run: |
          source /tmp/torchani-ci/bin/activate
          python setup.py install
    - name: Download data files
      run: ./download.sh
    - name: Run all tests
      run: |
          source /tmp/torchani-ci/bin/activate
          python -m pytest -v tests/*
    - name: remove venv
      if: always()
      run: rm -rf /tmp/torchani-ci/
