name: unittests-cpu

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unittests-cpu:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install pip
        run: pip install --upgrade pip

      - name: Install setuptools
        run: pip install 'setuptools>=61' 'setuptools_scm>=8'

      - name: Install tests requirements
        run: pip install -r tests_requirements.txt

      - name: Download data
        run: cd ./torchani_sandbox && ./download.sh

      - name: Install torchani
        run: pip install --no-build-isolation --editable ./torchani_sandbox

      - name: Run tests
        run: cd ./torchani_sandbox/tests && pytest -s -v .

concurrency:
  group: unittests-cpu-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
