name: unittests-cpu

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unittests-cpu:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
      options: --rm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install and Run tests
        run: >-
            "mkdir -p /torchani_sandbox
            && cd /torchani_sandbox
            && pip install --upgrade pip
            && pip install 'setuptools>=61' 'setuptools_scm>=8'
            && pip install -r tests_requirements.txt
            && ./download.sh
            && pip install --no-build-isolation --editable .
            && cd tests/
            && pytest -s -v ."
concurrency:
  group: unittests-cpu-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
