name: unittests-cpu

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unittests-cpu:
    runs-on: [self-hosted, ipickering]

    steps:
      - name: Checkout torchani
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Install and Run tests
        run: >-
            docker run
            --rm
            --gpus '"device=none"'
            --ipc=host
            -v $PWD:/examples pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel
            bash
            -c
            "mkdir -p /torchani_sandbox
            && cd /torchani_sandbox
            && apt-get update
            && apt-get install -y git wget unzip
            && cp -r /examples/. /torchani_sandbox/
            && pip install --progress-bar off 'setuptools>=61' 'setuptools_scm>=8'
            && pip install --progress-bar off -r tests_requirements.txt
            && ./download.sh
            && pip install --progress-bar off -e .
            && cd tests/
            && pytest -s -v ."

concurrency:
  group: unittests-cpu-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
