# upgrade torch-nightly on self-hosted runner
name: upgrade-torch-nightly

on:
  pull_request:
  schedule:
    - cron: '6 0 * * 6'

jobs:
  upgrade-torch-nightly:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.6]
        runner: [1, 2, 3, 4]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade torch-nightly
      run: |
        file_size=$(du -bs $(pip cache dir) | cut -f1)
        du -bsh $(pip cache dir)
        if [[ $file_size -gt 10737418240 ]]; then pip cache purge; fi
        pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html --upgrade

concurrency:
  group: upgrade-torch-nightly
  cancel-in-progress: true